version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: lxml
    versions:
    - 4.6.3
  - dependency-name: python-telegram-bot
    versions:
    - "13.3"
    - 13.4.1
  - dependency-name: googletrans
    versions:
    - 4.0.0rc1
